### ISSUE TITLE
E2E tests Framework

### ISSUE THREAD

**Issue by nekoyama** [nekoyama/preciosita#2]
## Rationale 
This issue aims to document the effort and tasks needed to implement an Automated Framework that should run our E2E tests. 

## Acceptance Criteria:

Specifications: 
- [x] Choose the technology.
- [x] Create a npm package. https://github.com/nekoyama/preciosita
- [x] Get the first test script to run locally.
- [ ] Be sure that it works on IE #371 
- [ ] Run the E2E tests on a installed nuget package. Spike #368
- [ ] Write documentation: choose scenarios to be covered.  #365
- [ ] Spike DATA generation. (Mocking).
- [ ] Check with the DevOps about integration to CI build.
